apiVersion: v1
kind: ServiceAccount
metadata:
  name: netboot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netboot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netboot
subjects:
- kind: ServiceAccount
  name: netboot
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netboot
  template:
    metadata:
      labels:
        app: netboot
    spec:
      containers:
      - name: netboot
        image: $USER.azurecr.io/netboot:latest
      hostNetwork: true
      serviceAccountName: netboot
