---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netboot
rules:
- apiGroups:
  - dummy.group
  resources:
  - machines
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: netboot
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
