#!/bin/sh -e

if [ "$1" = prereqs ]; then
    echo
    exit 0
fi

. /scripts/functions

for arg in $(cat /proc/cmdline); do
	case $arg in
        stage2=*)
            stage2="${arg#stage2=}"
            ;;
        ds=*)
            ds="${arg#ds=}"
            ;;
	esac
done

if [ -z "$stage2" ]; then
    panic "stage2= not set on cmdline"
fi

if [ -z "$ds" ]; then
    panic "ds= not set on cmdline"
fi

configure_networking

for i in /sys/block/*; do
	case $(readlink "$i") in
        ../devices/virtual/*)
            ;;
        *)
            dev=/dev/$(basename "$i")
            break
	esac
done

# TODO: validate this image as it's received
curl "$stage2" | gunzip >"$dev"

blockdev --rereadpt "$dev"

mount "${dev}1" /root
mount --bind /dev /root/dev
mount --bind /proc /root/proc

cat >/root/etc/default/grub.d/90-stage2.cfg <<EOF
GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 'ds=$ds'"
EOF

chroot /root update-grub

umount /root/proc
umount /root/dev
umount /root

sync

reboot -f
